[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:sdhrt/nvim-config.git"
    refreshPeriod = "24h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"

[".config/tmux/plugins/tmux-dotbar/dotbar.tmux"]
    type = "git-repo"
    url = "https://github.com/vaaleyard/tmux-dotbar"
