# General
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

# Change prefix from ctrl b to ctrl a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# mouse mode
set -g mouse on

unbind %
bind a split-window -h

# start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

set -g status-bg "#7EC8E3"
set -g status-fg "#26201B" 
set -g pane-active-border-style "fg=#8C7C6D"

# bind r source-file ~/.config/tmux/.tmux.conf; display-message "config reloaded"
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# resizing
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10
