# set -g default-terminal "xterm-256color"
# set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ',*-256color*:Tc'

# Setting the prefix from C-b to C-a
set -g prefix C-a

setw -g mouse on

# Free the original Ctrl-b prefix keybinding
unbind C-b

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
set -g pane-base-index 1

# Set bind key to reload configuration file
bind r source-file ~/.tmux.conf \; display ​"Reloaded!"

# splitting panes with | and -
bind h split-window -h
bind v split-window -v

# unbind switch pane with C-0
unbind C-o


# Set nvim as the default editor
set -g status-keys vi 

# set the status line's colors
set -g status-style fg=colour244,bg=colour234

# active pane style
set -g pane-active-border-style fg=colour244,bg=colour234
