# set tmux color
set-option -sa terminal-overrides ",xterm-256color:RGB"
set -g default-terminal tmux-256color
set -g status-bg "#7EC8E3" 
set -g status-fg "#26201B" 

set -g pane-active-border-style "fg=#8C7C6D"

# prefix has been set to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

#setting mouse on
set -g mouse on

#set history
set -g history-limit 5000

# clear both screen and history
bind -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history

# unbinding default split hotkey
unbind '"'
unbind %
bind [ split-window -h
bind ] split-window -v

# open new window in current path
bind c new-window -c "#{pane_current_path}"

bind r source-file ~/.config/tmux/tmux.conf

# resizing
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10

unbind C-o
